# Generated by Django 4.2.7 on 2023-12-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='examstatus',
            field=models.IntegerField(default=0),
        ),
    ]
