# Generated by Django 4.2.5 on 2023-12-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_work',
            name='semester',
            field=models.CharField(default='', max_length=100),
        ),
    ]
