# Generated by Django 4.2.7 on 2023-12-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('staffwork', '0002_add_work_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_work',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.semesters'),
        ),
    ]
