# Generated by Django 4.2.5 on 2023-11-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(default='', max_length=50)),
                ('seatrows', models.IntegerField(default='')),
                ('seatcolumns', models.IntegerField(default='')),
                ('strength', models.IntegerField(null=True)),
            ],
        ),
    ]
