# Generated by Django 4.2.5 on 2023-11-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
