# Generated by Django 4.2.5 on 2023-11-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_notes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notes',
        ),
    ]
