# Generated by Django 4.2.5 on 2023-11-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_remove_notes_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
