# Generated by Django 4.2.5 on 2023-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_alter_notes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
