# Generated by Django 4.2.5 on 2023-11-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('subject', '0007_alter_notes_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.departments'),
        ),
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.CharField(default='', max_length=500),
        ),
    ]
