# Generated by Django 4.2.5 on 2023-12-01 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_notes_department_notes_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='semester',
        ),
    ]
