# Generated by Django 4.2.5 on 2023-12-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_remove_notes_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
    ]
