# Generated by Django 4.2.7 on 2023-12-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_alter_subjects_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
