# Generated by Django 4.2.7 on 2023-12-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_alter_notes_description_alter_notes_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
