# Generated by Django 4.2.5 on 2023-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0016_alter_notes_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notes',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
